window.ITEMS = {
  // TOOLS
  wooden_pickaxe: { name: "Wooden Pickaxe", category: "Tools", textureType: "item", textureName: "wooden_pickaxe" },
  stone_pickaxe: { name: "Stone Pickaxe", category: "Tools", textureType: "item", textureName: "stone_pickaxe" },
  iron_pickaxe: { name: "Iron Pickaxe", category: "Tools", textureType: "item", textureName: "iron_pickaxe" },
  golden_pickaxe: { name: "Golden Pickaxe", category: "Tools", textureType: "item", textureName: "golden_pickaxe" },
  diamond_pickaxe: { name: "Diamond Pickaxe", category: "Tools", textureType: "item", textureName: "diamond_pickaxe" },
  netherite_pickaxe: { name: "Netherite Pickaxe", category: "Tools", textureType: "item", textureName: "netherite_pickaxe", craftable: false },
  wooden_sword: { name: "Wooden Sword", category: "Combat", textureType: "item", textureName: "wooden_sword" },
  stone_sword: { name: "Stone Sword", category: "Combat", textureType: "item", textureName: "stone_sword" },
  iron_sword: { name: "Iron Sword", category: "Combat", textureType: "item", textureName: "iron_sword" },
  golden_sword: { name: "Golden Sword", category: "Combat", textureType: "item", textureName: "golden_sword" },
  diamond_sword: { name: "Diamond Sword", category: "Combat", textureType: "item", textureName: "diamond_sword" },
  netherite_sword: { name: "Netherite Sword", category: "Combat", textureType: "item", textureName: "netherite_sword", craftable: false },
  wooden_axe: { name: "Wooden Axe", category: "Tools", textureType: "item", textureName: "wooden_axe" },
  stone_axe: { name: "Stone Axe", category: "Tools", textureType: "item", textureName: "stone_axe" },
  iron_axe: { name: "Iron Axe", category: "Tools", textureType: "item", textureName: "iron_axe" },
  golden_axe: { name: "Golden Axe", category: "Tools", textureType: "item", textureName: "golden_axe" },
  diamond_axe: { name: "Diamond Axe", category: "Tools", textureType: "item", textureName: "diamond_axe" },
  wooden_shovel: { name: "Wooden Shovel", category: "Tools", textureType: "item", textureName: "wooden_shovel" },
  stone_shovel: { name: "Stone Shovel", category: "Tools", textureType: "item", textureName: "stone_shovel" },
  iron_shovel: { name: "Iron Shovel", category: "Tools", textureType: "item", textureName: "iron_shovel" },
  golden_shovel: { name: "Golden Shovel", category: "Tools", textureType: "item", textureName: "golden_shovel" },
  diamond_shovel: { name: "Diamond Shovel", category: "Tools", textureType: "item", textureName: "diamond_shovel" },
  wooden_hoe: { name: "Wooden Hoe", category: "Tools", textureType: "item", textureName: "wooden_hoe" },
  stone_hoe: { name: "Stone Hoe", category: "Tools", textureType: "item", textureName: "stone_hoe" },
  iron_hoe: { name: "Iron Hoe", category: "Tools", textureType: "item", textureName: "iron_hoe" },
  golden_hoe: { name: "Golden Hoe", category: "Tools", textureType: "item", textureName: "golden_hoe" },
  diamond_hoe: { name: "Diamond Hoe", category: "Tools", textureType: "item", textureName: "diamond_hoe" },
  // ARMOR
  leather_helmet: { name: "Leather Helmet", category: "Armor", textureType: "item", textureName: "leather_helmet" },
  leather_chestplate: { name: "Leather Chestplate", category: "Armor", textureType: "item", textureName: "leather_chestplate" },
  leather_leggings: { name: "Leather Leggings", category: "Armor", textureType: "item", textureName: "leather_leggings" },
  leather_boots: { name: "Leather Boots", category: "Armor", textureType: "item", textureName: "leather_boots" },
  iron_helmet: { name: "Iron Helmet", category: "Armor", textureType: "item", textureName: "iron_helmet" },
  iron_chestplate: { name: "Iron Chestplate", category: "Armor", textureType: "item", textureName: "iron_chestplate" },
  iron_leggings: { name: "Iron Leggings", category: "Armor", textureType: "item", textureName: "iron_leggings" },
  iron_boots: { name: "Iron Boots", category: "Armor", textureType: "item", textureName: "iron_boots" },
  golden_helmet: { name: "Golden Helmet", category: "Armor", textureType: "item", textureName: "golden_helmet" },
  golden_chestplate: { name: "Golden Chestplate", category: "Armor", textureType: "item", textureName: "golden_chestplate" },
  golden_leggings: { name: "Golden Leggings", category: "Armor", textureType: "item", textureName: "golden_leggings" },
  golden_boots: { name: "Golden Boots", category: "Armor", textureType: "item", textureName: "golden_boots" },
  diamond_helmet: { name: "Diamond Helmet", category: "Armor", textureType: "item", textureName: "diamond_helmet" },
  diamond_chestplate: { name: "Diamond Chestplate", category: "Armor", textureType: "item", textureName: "diamond_chestplate" },
  diamond_leggings: { name: "Diamond Leggings", category: "Armor", textureType: "item", textureName: "diamond_leggings" },
  diamond_boots: { name: "Diamond Boots", category: "Armor", textureType: "item", textureName: "diamond_boots" },
  chainmail_helmet: { name: "Chainmail Helmet", category: "Armor", textureType: "item", textureName: "chainmail_helmet", craftable: false },
  chainmail_chestplate: { name: "Chainmail Chestplate", category: "Armor", textureType: "item", textureName: "chainmail_chestplate", craftable: false },
  chainmail_leggings: { name: "Chainmail Leggings", category: "Armor", textureType: "item", textureName: "chainmail_leggings", craftable: false },
  chainmail_boots: { name: "Chainmail Boots", category: "Armor", textureType: "item", textureName: "chainmail_boots", craftable: false },
  // PLANKS
  oak_planks: { name: "Oak Planks", category: "Building", textureType: "block", textureName: "oak_planks" },
  birch_planks: { name: "Birch Planks", category: "Building", textureType: "block", textureName: "birch_planks" },
  spruce_planks: { name: "Spruce Planks", category: "Building", textureType: "block", textureName: "spruce_planks" },
  jungle_planks: { name: "Jungle Planks", category: "Building", textureType: "block", textureName: "jungle_planks" },
  acacia_planks: { name: "Acacia Planks", category: "Building", textureType: "block", textureName: "acacia_planks" },
  dark_oak_planks: { name: "Dark Oak Planks", category: "Building", textureType: "block", textureName: "dark_oak_planks" },
  mangrove_planks: { name: "Mangrove Planks", category: "Building", textureType: "block", textureName: "mangrove_planks" },
  cherry_planks: { name: "Cherry Planks", category: "Building", textureType: "block", textureName: "cherry_planks" },
  bamboo_planks: { name: "Bamboo Planks", category: "Building", textureType: "block", textureName: "bamboo_planks" },
  crimson_planks: { name: "Crimson Planks", category: "Building", textureType: "block", textureName: "crimson_planks" },
  warped_planks: { name: "Warped Planks", category: "Building", textureType: "block", textureName: "warped_planks" },
  // LOGS
  oak_log: { name: "Oak Log", category: "Building", textureType: "block", textureName: "oak_log" },
  birch_log: { name: "Birch Log", category: "Building", textureType: "block", textureName: "birch_log" },
  spruce_log: { name: "Spruce Log", category: "Building", textureType: "block", textureName: "spruce_log" },
  jungle_log: { name: "Jungle Log", category: "Building", textureType: "block", textureName: "jungle_log" },
  acacia_log: { name: "Acacia Log", category: "Building", textureType: "block", textureName: "acacia_log" },
  dark_oak_log: { name: "Dark Oak Log", category: "Building", textureType: "block", textureName: "dark_oak_log" },
  mangrove_log: { name: "Mangrove Log", category: "Building", textureType: "block", textureName: "mangrove_log" },
  // BASIC
  stick: { name: "Stick", category: "Utility", textureType: "item", textureName: "stick" },
  crafting_table: { name: "Crafting Table", category: "Utility", textureType: "block", textureName: "crafting_table_front" },
  furnace: { name: "Furnace", category: "Utility", textureType: "block", textureName: "furnace_front" },
  chest: { name: "Chest", category: "Utility", textureType: "block", textureName: "chest" },
  // BUILDING BLOCKS
  stone: { name: "Stone", category: "Building", textureType: "block", textureName: "stone" },
  cobblestone: { name: "Cobblestone", category: "Building", textureType: "block", textureName: "cobblestone" },
  stone_bricks: { name: "Stone Bricks", category: "Building", textureType: "block", textureName: "stone_bricks" },
  bricks: { name: "Bricks", category: "Building", textureType: "block", textureName: "bricks" },
  sandstone: { name: "Sandstone", category: "Building", textureType: "block", textureName: "sandstone" },
  chiseled_sandstone: { name: "Chiseled Sandstone", category: "Building", textureType: "block", textureName: "chiseled_sandstone" },
  quartz_block: { name: "Quartz Block", category: "Building", textureType: "block", textureName: "quartz_block_top" },
  nether_brick: { name: "Nether Brick", category: "Building", textureType: "block", textureName: "nether_bricks" },
  glass: { name: "Glass", category: "Building", textureType: "block", textureName: "glass" },
  glass_pane: { name: "Glass Pane", category: "Building", textureType: "block", textureName: "glass_pane_top" },
  iron_bars: { name: "Iron Bars", category: "Building", textureType: "block", textureName: "iron_bars" },
  polished_granite: { name: "Polished Granite", category: "Building", textureType: "block", textureName: "polished_granite" },
  polished_diorite: { name: "Polished Diorite", category: "Building", textureType: "block", textureName: "polished_diorite" },
  polished_andesite: { name: "Polished Andesite", category: "Building", textureType: "block", textureName: "polished_andesite" },
  granite: { name: "Granite", category: "Building", textureType: "block", textureName: "granite" },
  diorite: { name: "Diorite", category: "Building", textureType: "block", textureName: "diorite" },
  andesite: { name: "Andesite", category: "Building", textureType: "block", textureName: "andesite" },
  smooth_stone: { name: "Smooth Stone", category: "Building", textureType: "block", textureName: "smooth_stone" },
  smooth_stone_slab: { name: "Smooth Stone Slab", category: "Building", textureType: "block", textureName: "smooth_stone" },
  obsidian: { name: "Obsidian", category: "Building", textureType: "block", textureName: "obsidian" },
  snow_block: { name: "Snow Block", category: "Building", textureType: "block", textureName: "snow" },
  iron_block: { name: "Iron Block", category: "Building", textureType: "block", textureName: "iron_block" },
  gold_block: { name: "Gold Block", category: "Building", textureType: "block", textureName: "gold_block" },
  diamond_block: { name: "Diamond Block", category: "Building", textureType: "block", textureName: "diamond_block" },
  nether_brick_block: { name: "Nether Brick Block", category: "Building", textureType: "block", textureName: "nether_bricks" },
  // FOOD
  bread: { name: "Bread", category: "Food", textureType: "item", textureName: "bread" },
  cookie: { name: "Cookie", category: "Food", textureType: "item", textureName: "cookie" },
  cake: { name: "Cake", category: "Food", textureType: "block", textureName: "cake_top" },
  pumpkin_pie: { name: "Pumpkin Pie", category: "Food", textureType: "item", textureName: "pumpkin_pie" },
  golden_apple: { name: "Golden Apple", category: "Food", textureType: "item", textureName: "golden_apple" },
  golden_carrot: { name: "Golden Carrot", category: "Food", textureType: "item", textureName: "golden_carrot" },
  mushroom_stew: { name: "Mushroom Stew", category: "Food", textureType: "item", textureName: "mushroom_stew" },
  wheat: { name: "Wheat", category: "Food", textureType: "item", textureName: "wheat" },
  // UTILITY
  smoker: { name: "Smoker", category: "Utility", textureType: "block", textureName: "smoker_front" },
  blast_furnace: { name: "Blast Furnace", category: "Utility", textureType: "block", textureName: "blast_furnace_front" },
  barrel: { name: "Barrel", category: "Utility", textureType: "block", textureName: "barrel_top" },
  hopper: { name: "Hopper", category: "Utility", textureType: "block", textureName: "hopper_outside" },
  dropper: { name: "Dropper", category: "Utility", textureType: "block", textureName: "dropper_front" },
  dispenser: { name: "Dispenser", category: "Utility", textureType: "block", textureName: "dispenser_front" },
  anvil: { name: "Anvil", category: "Utility", textureType: "block", textureName: "anvil_top" },
  beacon: { name: "Beacon", category: "Utility", textureType: "block", textureName: "beacon" },
  book: { name: "Book", category: "Utility", textureType: "item", textureName: "book" },
  torch: { name: "Torch", category: "Utility", textureType: "block", textureName: "torch" },
  ladder: { name: "Ladder", category: "Utility", textureType: "block", textureName: "ladder" },
  scaffolding: { name: "Scaffolding", category: "Utility", textureType: "block", textureName: "scaffolding_top" },
  lead: { name: "Lead", category: "Utility", textureType: "item", textureName: "lead" },
  name_tag: { name: "Name Tag", category: "Utility", textureType: "item", textureName: "name_tag", craftable: false },
  paper: { name: "Paper", category: "Utility", textureType: "item", textureName: "paper" },
  bucket: { name: "Bucket", category: "Utility", textureType: "item", textureName: "bucket" },
  clock: { name: "Clock", category: "Utility", textureType: "item", textureName: "clock_00" },
  compass: { name: "Compass", category: "Utility", textureType: "item", textureName: "compass_00" },
  map: { name: "Map", category: "Utility", textureType: "item", textureName: "map" },
  lectern: { name: "Lectern", category: "Utility", textureType: "block", textureName: "lectern_top" },
  // MAGIC
  enchanting_table: { name: "Enchanting Table", category: "Magic", textureType: "block", textureName: "enchanting_table_top" },
  brewing_stand: { name: "Brewing Stand", category: "Magic", textureType: "block", textureName: "brewing_stand" },
  cauldron: { name: "Cauldron", category: "Magic", textureType: "block", textureName: "cauldron_inner" },
  end_crystal: { name: "End Crystal", category: "Magic", textureType: "item", textureName: "end_crystal" },
  eye_of_ender: { name: "Eye of Ender", category: "Magic", textureType: "item", textureName: "ender_eye" },
  fire_charge: { name: "Fire Charge", category: "Magic", textureType: "item", textureName: "fire_charge" },
  nether_star: { name: "Nether Star", category: "Magic", textureType: "item", textureName: "nether_star" },
  blaze_rod: { name: "Blaze Rod", category: "Magic", textureType: "item", textureName: "blaze_rod" },
  // REDSTONE
  repeater: { name: "Repeater", category: "Redstone", textureType: "item", textureName: "repeater" },
  comparator: { name: "Comparator", category: "Redstone", textureType: "item", textureName: "comparator" },
  piston: { name: "Piston", category: "Redstone", textureType: "block", textureName: "piston_top_normal" },
  sticky_piston: { name: "Sticky Piston", category: "Redstone", textureType: "block", textureName: "piston_top_sticky" },
  lever: { name: "Lever", category: "Redstone", textureType: "block", textureName: "lever" },
  stone_button: { name: "Stone Button", category: "Redstone", textureType: "block", textureName: "stone" },
  oak_button: { name: "Oak Button", category: "Redstone", textureType: "block", textureName: "oak_planks" },
  stone_pressure_plate: { name: "Stone Pressure Plate", category: "Redstone", textureType: "block", textureName: "stone_pressure_plate" },
  oak_pressure_plate: { name: "Oak Pressure Plate", category: "Redstone", textureType: "block", textureName: "oak_pressure_plate" },
  birch_pressure_plate: { name: "Birch Pressure Plate", category: "Redstone", textureType: "block", textureName: "birch_planks" },
  tripwire_hook: { name: "Tripwire Hook", category: "Redstone", textureType: "item", textureName: "tripwire_hook" },
  daylight_detector: { name: "Daylight Detector", category: "Redstone", textureType: "block", textureName: "daylight_detector_top" },
  observer: { name: "Observer", category: "Redstone", textureType: "block", textureName: "observer_front" },
  target: { name: "Target", category: "Redstone", textureType: "block", textureName: "target_top" },
  redstone_torch: { name: "Redstone Torch", category: "Redstone", textureType: "block", textureName: "redstone_torch" },
  redstone: { name: "Redstone Dust", category: "Redstone", textureType: "item", textureName: "redstone" },
  redstone_lamp: { name: "Redstone Lamp", category: "Redstone", textureType: "block", textureName: "redstone_lamp" },
  // COMBAT
  bow: { name: "Bow", category: "Combat", textureType: "item", textureName: "bow" },
  crossbow: { name: "Crossbow", category: "Combat", textureType: "item", textureName: "crossbow_standby" },
  shield: { name: "Shield", category: "Combat", textureType: "item", textureName: "shield" },
  arrow: { name: "Arrow", category: "Combat", textureType: "item", textureName: "arrow" },
  tnt: { name: "TNT", category: "Combat", textureType: "block", textureName: "tnt_side" },
  // DECORATION
  painting: { name: "Painting", category: "Decoration", textureType: "item", textureName: "painting" },
  item_frame: { name: "Item Frame", category: "Decoration", textureType: "item", textureName: "item_frame" },
  flower_pot: { name: "Flower Pot", category: "Decoration", textureType: "item", textureName: "flower_pot" },
  armor_stand: { name: "Armor Stand", category: "Decoration", textureType: "item", textureName: "armor_stand" },
  bookshelf: { name: "Bookshelf", category: "Decoration", textureType: "block", textureName: "bookshelf" },
  lantern: { name: "Lantern", category: "Decoration", textureType: "block", textureName: "lantern" },
  soul_lantern: { name: "Soul Lantern", category: "Decoration", textureType: "block", textureName: "soul_lantern" },
  campfire: { name: "Campfire", category: "Decoration", textureType: "block", textureName: "campfire_fire" },
  jukebox: { name: "Jukebox", category: "Decoration", textureType: "block", textureName: "jukebox_top" },
  note_block: { name: "Note Block", category: "Decoration", textureType: "block", textureName: "note_block" },
  white_wool: { name: "White Wool", category: "Decoration", textureType: "block", textureName: "white_wool" },
  white_carpet: { name: "White Carpet", category: "Decoration", textureType: "block", textureName: "white_carpet" },
  white_banner: { name: "White Banner", category: "Decoration", textureType: "item", textureName: "white_banner" },
  white_bed: { name: "White Bed", category: "Decoration", textureType: "item", textureName: "white_bed" },
  oak_sign: { name: "Oak Sign", category: "Decoration", textureType: "item", textureName: "oak_sign" },
  // TRANSPORTATION
  oak_boat: { name: "Oak Boat", category: "Transportation", textureType: "item", textureName: "oak_boat" },
  minecart: { name: "Minecart", category: "Transportation", textureType: "item", textureName: "minecart" },
  chest_minecart: { name: "Chest Minecart", category: "Transportation", textureType: "item", textureName: "chest_minecart" },
  furnace_minecart: { name: "Furnace Minecart", category: "Transportation", textureType: "item", textureName: "furnace_minecart" },
  saddle: { name: "Saddle", category: "Transportation", textureType: "item", textureName: "saddle", craftable: false },
  // BUILDING - DOORS/FENCES/SLABS
  oak_door: { name: "Oak Door", category: "Building", textureType: "item", textureName: "oak_door" },
  iron_door: { name: "Iron Door", category: "Building", textureType: "item", textureName: "iron_door" },
  oak_trapdoor: { name: "Oak Trapdoor", category: "Building", textureType: "block", textureName: "oak_trapdoor" },
  iron_trapdoor: { name: "Iron Trapdoor", category: "Building", textureType: "item", textureName: "iron_trapdoor" },
  oak_slab: { name: "Oak Slab", category: "Building", textureType: "block", textureName: "oak_planks" },
  stone_slab: { name: "Stone Slab", category: "Building", textureType: "block", textureName: "stone" },
  oak_stairs: { name: "Oak Stairs", category: "Building", textureType: "block", textureName: "oak_planks" },
  stone_stairs: { name: "Stone Stairs", category: "Building", textureType: "block", textureName: "stone" },
  oak_fence: { name: "Oak Fence", category: "Building", textureType: "block", textureName: "oak_planks" },
  oak_fence_gate: { name: "Oak Fence Gate", category: "Building", textureType: "block", textureName: "oak_planks" },
  // TOOLS (more)
  fishing_rod: { name: "Fishing Rod", category: "Tools", textureType: "item", textureName: "fishing_rod_uncast" },
  flint_and_steel: { name: "Flint and Steel", category: "Tools", textureType: "item", textureName: "flint_and_steel" },
  shears: { name: "Shears", category: "Tools", textureType: "item", textureName: "shears" },
  // INGREDIENT ITEMS (raw materials / mob drops)
  iron_ingot: { name: "Iron Ingot", category: "Materials", textureType: "item", textureName: "iron_ingot" },
  gold_ingot: { name: "Gold Ingot", category: "Materials", textureType: "item", textureName: "gold_ingot" },
  diamond: { name: "Diamond", category: "Materials", textureType: "item", textureName: "diamond" },
  leather: { name: "Leather", category: "Materials", textureType: "item", textureName: "leather" },
  coal: { name: "Coal", category: "Materials", textureType: "item", textureName: "coal" },
  brick_item: { name: "Brick", category: "Materials", textureType: "item", textureName: "brick" },
  sand: { name: "Sand", category: "Building", textureType: "block", textureName: "sand" },
  quartz: { name: "Nether Quartz", category: "Materials", textureType: "item", textureName: "quartz" },
  cocoa_beans: { name: "Cocoa Beans", category: "Materials", textureType: "item", textureName: "cocoa_beans" },
  milk_bucket: { name: "Milk Bucket", category: "Materials", textureType: "item", textureName: "milk_bucket" },
  sugar: { name: "Sugar", category: "Materials", textureType: "item", textureName: "sugar" },
  egg: { name: "Egg", category: "Materials", textureType: "item", textureName: "egg" },
  pumpkin: { name: "Pumpkin", category: "Building", textureType: "block", textureName: "pumpkin_top" },
  apple: { name: "Apple", category: "Food", textureType: "item", textureName: "apple" },
  carrot: { name: "Carrot", category: "Food", textureType: "item", textureName: "carrot" },
  gold_nugget: { name: "Gold Nugget", category: "Materials", textureType: "item", textureName: "gold_nugget" },
  iron_nugget: { name: "Iron Nugget", category: "Materials", textureType: "item", textureName: "iron_nugget" },
  red_mushroom: { name: "Red Mushroom", category: "Food", textureType: "block", textureName: "red_mushroom" },
  brown_mushroom: { name: "Brown Mushroom", category: "Food", textureType: "block", textureName: "brown_mushroom" },
  bowl: { name: "Bowl", category: "Utility", textureType: "item", textureName: "bowl" },
  slimeball: { name: "Slimeball", category: "Materials", textureType: "item", textureName: "slimeball" },
  hay_bale: { name: "Hay Bale", category: "Building", textureType: "block", textureName: "hay_block_top" },
  string: { name: "String", category: "Materials", textureType: "item", textureName: "string" },
  feather: { name: "Feather", category: "Materials", textureType: "item", textureName: "feather" },
  flint: { name: "Flint", category: "Materials", textureType: "item", textureName: "flint" },
  gunpowder: { name: "Gunpowder", category: "Materials", textureType: "item", textureName: "gunpowder" },
  glowstone: { name: "Glowstone", category: "Building", textureType: "block", textureName: "glowstone" },
  snowball: { name: "Snowball", category: "Materials", textureType: "item", textureName: "snowball" },
  ender_pearl: { name: "Ender Pearl", category: "Materials", textureType: "item", textureName: "ender_pearl" },
  blaze_powder: { name: "Blaze Powder", category: "Materials", textureType: "item", textureName: "blaze_powder" },
  ghast_tear: { name: "Ghast Tear", category: "Materials", textureType: "item", textureName: "ghast_tear" },
  sugar_cane: { name: "Sugar Cane", category: "Building", textureType: "block", textureName: "sugar_cane" },
};
