window.RECIPES = [
  // PLANKS from logs
  { id: "oak_planks", resultId: "oak_planks", resultCount: 4, type: "shapeless", gridSize: "2x2", pattern: ["oak_log", null, null, null] },
  { id: "birch_planks", resultId: "birch_planks", resultCount: 4, type: "shapeless", gridSize: "2x2", pattern: ["birch_log", null, null, null] },
  { id: "spruce_planks", resultId: "spruce_planks", resultCount: 4, type: "shapeless", gridSize: "2x2", pattern: ["spruce_log", null, null, null] },
  { id: "jungle_planks", resultId: "jungle_planks", resultCount: 4, type: "shapeless", gridSize: "2x2", pattern: ["jungle_log", null, null, null] },
  { id: "acacia_planks", resultId: "acacia_planks", resultCount: 4, type: "shapeless", gridSize: "2x2", pattern: ["acacia_log", null, null, null] },
  { id: "dark_oak_planks", resultId: "dark_oak_planks", resultCount: 4, type: "shapeless", gridSize: "2x2", pattern: ["dark_oak_log", null, null, null] },
  { id: "mangrove_planks", resultId: "mangrove_planks", resultCount: 4, type: "shapeless", gridSize: "2x2", pattern: ["mangrove_log", null, null, null] },
  // STICKS
  { id: "stick", resultId: "stick", resultCount: 4, type: "shaped", gridSize: "2x2", pattern: ["oak_planks", null, "oak_planks", null] },
  // CRAFTING TABLE
  { id: "crafting_table", resultId: "crafting_table", resultCount: 1, type: "shaped", gridSize: "2x2", pattern: ["oak_planks", "oak_planks", "oak_planks", "oak_planks"] },
  // PICKAXES
  { id: "wooden_pickaxe", resultId: "wooden_pickaxe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","oak_planks","oak_planks", null,"stick",null, null,"stick",null] },
  { id: "stone_pickaxe", resultId: "stone_pickaxe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["cobblestone","cobblestone","cobblestone", null,"stick",null, null,"stick",null] },
  { id: "iron_pickaxe", resultId: "iron_pickaxe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_ingot","iron_ingot","iron_ingot", null,"stick",null, null,"stick",null] },
  { id: "golden_pickaxe", resultId: "golden_pickaxe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["gold_ingot","gold_ingot","gold_ingot", null,"stick",null, null,"stick",null] },
  { id: "diamond_pickaxe", resultId: "diamond_pickaxe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["diamond","diamond","diamond", null,"stick",null, null,"stick",null] },
  // SWORDS
  { id: "wooden_sword", resultId: "wooden_sword", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"oak_planks",null, null,"oak_planks",null, null,"stick",null] },
  { id: "stone_sword", resultId: "stone_sword", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"cobblestone",null, null,"cobblestone",null, null,"stick",null] },
  { id: "iron_sword", resultId: "iron_sword", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"iron_ingot",null, null,"iron_ingot",null, null,"stick",null] },
  { id: "golden_sword", resultId: "golden_sword", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"gold_ingot",null, null,"gold_ingot",null, null,"stick",null] },
  { id: "diamond_sword", resultId: "diamond_sword", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"diamond",null, null,"diamond",null, null,"stick",null] },
  // AXES
  { id: "wooden_axe", resultId: "wooden_axe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","oak_planks",null, "oak_planks","stick",null, null,"stick",null] },
  { id: "stone_axe", resultId: "stone_axe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["cobblestone","cobblestone",null, "cobblestone","stick",null, null,"stick",null] },
  { id: "iron_axe", resultId: "iron_axe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_ingot","iron_ingot",null, "iron_ingot","stick",null, null,"stick",null] },
  { id: "golden_axe", resultId: "golden_axe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["gold_ingot","gold_ingot",null, "gold_ingot","stick",null, null,"stick",null] },
  { id: "diamond_axe", resultId: "diamond_axe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["diamond","diamond",null, "diamond","stick",null, null,"stick",null] },
  // SHOVELS
  { id: "wooden_shovel", resultId: "wooden_shovel", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"oak_planks",null, null,"stick",null, null,"stick",null] },
  { id: "stone_shovel", resultId: "stone_shovel", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"cobblestone",null, null,"stick",null, null,"stick",null] },
  { id: "iron_shovel", resultId: "iron_shovel", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"iron_ingot",null, null,"stick",null, null,"stick",null] },
  { id: "golden_shovel", resultId: "golden_shovel", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"gold_ingot",null, null,"stick",null, null,"stick",null] },
  { id: "diamond_shovel", resultId: "diamond_shovel", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"diamond",null, null,"stick",null, null,"stick",null] },
  // HOES
  { id: "wooden_hoe", resultId: "wooden_hoe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","oak_planks",null, null,"stick",null, null,"stick",null] },
  { id: "stone_hoe", resultId: "stone_hoe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["cobblestone","cobblestone",null, null,"stick",null, null,"stick",null] },
  { id: "iron_hoe", resultId: "iron_hoe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_ingot","iron_ingot",null, null,"stick",null, null,"stick",null] },
  { id: "golden_hoe", resultId: "golden_hoe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["gold_ingot","gold_ingot",null, null,"stick",null, null,"stick",null] },
  { id: "diamond_hoe", resultId: "diamond_hoe", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["diamond","diamond",null, null,"stick",null, null,"stick",null] },
  // HELMETS
  { id: "leather_helmet", resultId: "leather_helmet", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["leather","leather","leather", "leather",null,"leather", null,null,null] },
  { id: "iron_helmet", resultId: "iron_helmet", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_ingot","iron_ingot","iron_ingot", "iron_ingot",null,"iron_ingot", null,null,null] },
  { id: "golden_helmet", resultId: "golden_helmet", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["gold_ingot","gold_ingot","gold_ingot", "gold_ingot",null,"gold_ingot", null,null,null] },
  { id: "diamond_helmet", resultId: "diamond_helmet", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["diamond","diamond","diamond", "diamond",null,"diamond", null,null,null] },
  // CHESTPLATES
  { id: "leather_chestplate", resultId: "leather_chestplate", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["leather",null,"leather", "leather","leather","leather", "leather","leather","leather"] },
  { id: "iron_chestplate", resultId: "iron_chestplate", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_ingot",null,"iron_ingot", "iron_ingot","iron_ingot","iron_ingot", "iron_ingot","iron_ingot","iron_ingot"] },
  { id: "golden_chestplate", resultId: "golden_chestplate", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["gold_ingot",null,"gold_ingot", "gold_ingot","gold_ingot","gold_ingot", "gold_ingot","gold_ingot","gold_ingot"] },
  { id: "diamond_chestplate", resultId: "diamond_chestplate", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["diamond",null,"diamond", "diamond","diamond","diamond", "diamond","diamond","diamond"] },
  // LEGGINGS
  { id: "leather_leggings", resultId: "leather_leggings", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["leather","leather","leather", "leather",null,"leather", "leather",null,"leather"] },
  { id: "iron_leggings", resultId: "iron_leggings", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_ingot","iron_ingot","iron_ingot", "iron_ingot",null,"iron_ingot", "iron_ingot",null,"iron_ingot"] },
  { id: "golden_leggings", resultId: "golden_leggings", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["gold_ingot","gold_ingot","gold_ingot", "gold_ingot",null,"gold_ingot", "gold_ingot",null,"gold_ingot"] },
  { id: "diamond_leggings", resultId: "diamond_leggings", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["diamond","diamond","diamond", "diamond",null,"diamond", "diamond",null,"diamond"] },
  // BOOTS
  { id: "leather_boots", resultId: "leather_boots", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "leather",null,"leather", "leather",null,"leather"] },
  { id: "iron_boots", resultId: "iron_boots", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "iron_ingot",null,"iron_ingot", "iron_ingot",null,"iron_ingot"] },
  { id: "golden_boots", resultId: "golden_boots", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "gold_ingot",null,"gold_ingot", "gold_ingot",null,"gold_ingot"] },
  { id: "diamond_boots", resultId: "diamond_boots", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "diamond",null,"diamond", "diamond",null,"diamond"] },
  // BUILDING
  { id: "furnace", resultId: "furnace", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["cobblestone","cobblestone","cobblestone", "cobblestone",null,"cobblestone", "cobblestone","cobblestone","cobblestone"] },
  { id: "chest", resultId: "chest", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","oak_planks","oak_planks", "oak_planks",null,"oak_planks", "oak_planks","oak_planks","oak_planks"] },
  { id: "stone_bricks", resultId: "stone_bricks", resultCount: 4, type: "shaped", gridSize: "2x2", pattern: ["stone","stone","stone","stone"] },
  { id: "sandstone", resultId: "sandstone", resultCount: 1, type: "shaped", gridSize: "2x2", pattern: ["sand","sand","sand","sand"], description: "Combine 4 sand blocks to craft 1 sandstone" },
  { id: "quartz_block", resultId: "quartz_block", resultCount: 1, type: "shaped", gridSize: "2x2", pattern: ["quartz","quartz","quartz","quartz"], description: "Craft 4 nether quartz into a block" },
  { id: "polished_granite", resultId: "polished_granite", resultCount: 4, type: "shaped", gridSize: "2x2", pattern: ["granite","granite","granite","granite"] },
  { id: "polished_diorite", resultId: "polished_diorite", resultCount: 4, type: "shaped", gridSize: "2x2", pattern: ["diorite","diorite","diorite","diorite"] },
  { id: "polished_andesite", resultId: "polished_andesite", resultCount: 4, type: "shaped", gridSize: "2x2", pattern: ["andesite","andesite","andesite","andesite"] },
  { id: "glass_pane", resultId: "glass_pane", resultCount: 16, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "glass","glass","glass", "glass","glass","glass"] },
  { id: "iron_bars", resultId: "iron_bars", resultCount: 16, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "iron_ingot","iron_ingot","iron_ingot", "iron_ingot","iron_ingot","iron_ingot"] },
  { id: "ladder", resultId: "ladder", resultCount: 3, type: "shaped", gridSize: "3x3", pattern: ["stick",null,"stick", "stick","stick","stick", "stick",null,"stick"] },
  { id: "torch", resultId: "torch", resultCount: 4, type: "shaped", gridSize: "2x2", pattern: ["coal", null, "stick", null], description: "Coal or charcoal on a stick" },
  { id: "lantern", resultId: "lantern", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_nugget","iron_nugget","iron_nugget", "iron_nugget","torch","iron_nugget", "iron_nugget","iron_nugget","iron_nugget"], description: "Surround a torch with iron nuggets" },
  { id: "campfire", resultId: "campfire", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"stick",null, "stick","coal","stick", "oak_log","oak_log","oak_log"] },
  { id: "iron_block", resultId: "iron_block", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_ingot","iron_ingot","iron_ingot", "iron_ingot","iron_ingot","iron_ingot", "iron_ingot","iron_ingot","iron_ingot"] },
  { id: "gold_block", resultId: "gold_block", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["gold_ingot","gold_ingot","gold_ingot", "gold_ingot","gold_ingot","gold_ingot", "gold_ingot","gold_ingot","gold_ingot"] },
  { id: "diamond_block", resultId: "diamond_block", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["diamond","diamond","diamond", "diamond","diamond","diamond", "diamond","diamond","diamond"] },
  { id: "snow_block", resultId: "snow_block", resultCount: 1, type: "shaped", gridSize: "2x2", pattern: ["snowball","snowball","snowball","snowball"], description: "Pack 4 snowballs into a snow block" },
  // WOODEN ITEMS
  { id: "oak_door", resultId: "oak_door", resultCount: 3, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","oak_planks",null, "oak_planks","oak_planks",null, "oak_planks","oak_planks",null] },
  { id: "oak_trapdoor", resultId: "oak_trapdoor", resultCount: 2, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "oak_planks","oak_planks","oak_planks", "oak_planks","oak_planks","oak_planks"] },
  { id: "oak_fence", resultId: "oak_fence", resultCount: 3, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "oak_planks","stick","oak_planks", "oak_planks","stick","oak_planks"] },
  { id: "oak_fence_gate", resultId: "oak_fence_gate", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "stick","oak_planks","stick", "stick","oak_planks","stick"] },
  { id: "oak_sign", resultId: "oak_sign", resultCount: 3, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","oak_planks","oak_planks", "oak_planks","oak_planks","oak_planks", null,"stick",null] },
  { id: "oak_slab", resultId: "oak_slab", resultCount: 6, type: "shaped", gridSize: "3x3", pattern: [null,null,null, null,null,null, "oak_planks","oak_planks","oak_planks"] },
  { id: "oak_stairs", resultId: "oak_stairs", resultCount: 4, type: "shaped", gridSize: "3x3", pattern: ["oak_planks",null,null, "oak_planks","oak_planks",null, "oak_planks","oak_planks","oak_planks"] },
  { id: "oak_pressure_plate", resultId: "oak_pressure_plate", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, null,null,null, "oak_planks","oak_planks",null] },
  { id: "oak_button", resultId: "oak_button", resultCount: 1, type: "shapeless", gridSize: "2x2", pattern: ["oak_planks",null,null,null] },
  { id: "bookshelf", resultId: "bookshelf", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","oak_planks","oak_planks", "book","book","book", "oak_planks","oak_planks","oak_planks"] },
  { id: "jukebox", resultId: "jukebox", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","oak_planks","oak_planks", "oak_planks","diamond","oak_planks", "oak_planks","oak_planks","oak_planks"] },
  { id: "note_block", resultId: "note_block", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","oak_planks","oak_planks", "oak_planks","redstone","oak_planks", "oak_planks","oak_planks","oak_planks"] },
  // IRON ITEMS
  { id: "iron_door", resultId: "iron_door", resultCount: 3, type: "shaped", gridSize: "3x3", pattern: ["iron_ingot","iron_ingot",null, "iron_ingot","iron_ingot",null, "iron_ingot","iron_ingot",null] },
  { id: "iron_trapdoor", resultId: "iron_trapdoor", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "iron_ingot","iron_ingot","iron_ingot", "iron_ingot","iron_ingot","iron_ingot"] },
  // STONE ITEMS
  { id: "stone_slab", resultId: "stone_slab", resultCount: 6, type: "shaped", gridSize: "3x3", pattern: [null,null,null, null,null,null, "stone","stone","stone"] },
  { id: "stone_stairs", resultId: "stone_stairs", resultCount: 4, type: "shaped", gridSize: "3x3", pattern: ["stone",null,null, "stone","stone",null, "stone","stone","stone"] },
  { id: "stone_pressure_plate", resultId: "stone_pressure_plate", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, null,null,null, "stone","stone",null] },
  { id: "stone_button", resultId: "stone_button", resultCount: 1, type: "shapeless", gridSize: "2x2", pattern: ["stone",null,null,null] },
  // FOOD
  { id: "bread", resultId: "bread", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "wheat","wheat","wheat", null,null,null] },
  { id: "cookie", resultId: "cookie", resultCount: 8, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "wheat","cocoa_beans","wheat", null,null,null], description: "Wheat with cocoa beans yields 8 cookies" },
  { id: "cake", resultId: "cake", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["milk_bucket","milk_bucket","milk_bucket", "sugar","egg","sugar", "wheat","wheat","wheat"], description: "3 milk buckets, 2 sugar, 1 egg, 3 wheat" },
  { id: "pumpkin_pie", resultId: "pumpkin_pie", resultCount: 1, type: "shapeless", gridSize: "3x3", pattern: ["pumpkin","sugar","egg",null,null,null,null,null,null], description: "Shapeless: pumpkin, sugar, egg" },
  { id: "golden_apple", resultId: "golden_apple", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["gold_ingot","gold_ingot","gold_ingot", "gold_ingot","apple","gold_ingot", "gold_ingot","gold_ingot","gold_ingot"], description: "8 gold ingots surrounding an apple" },
  { id: "golden_carrot", resultId: "golden_carrot", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["gold_nugget","gold_nugget","gold_nugget", "gold_nugget","carrot","gold_nugget", "gold_nugget","gold_nugget","gold_nugget"], description: "8 gold nuggets surrounding a carrot" },
  { id: "mushroom_stew", resultId: "mushroom_stew", resultCount: 1, type: "shapeless", gridSize: "2x2", pattern: ["red_mushroom","brown_mushroom","bowl",null], description: "Shapeless: red mushroom, brown mushroom, bowl" },
  // UTILITY
  { id: "barrel", resultId: "barrel", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","oak_slab","oak_planks", "oak_planks",null,"oak_planks", "oak_planks","oak_slab","oak_planks"] },
  { id: "smoker", resultId: "smoker", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"oak_log",null, "oak_log","furnace","oak_log", null,"oak_log",null] },
  { id: "blast_furnace", resultId: "blast_furnace", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_ingot","iron_ingot","iron_ingot", "iron_ingot","furnace","iron_ingot", "smooth_stone","smooth_stone","smooth_stone"] },
  { id: "hopper", resultId: "hopper", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_ingot",null,"iron_ingot", "iron_ingot","chest","iron_ingot", null,"iron_ingot",null] },
  { id: "dropper", resultId: "dropper", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["cobblestone","cobblestone","cobblestone", "cobblestone",null,"cobblestone", "cobblestone","redstone","cobblestone"] },
  { id: "dispenser", resultId: "dispenser", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["cobblestone","cobblestone","cobblestone", "cobblestone","bow","cobblestone", "cobblestone","redstone","cobblestone"] },
  { id: "anvil", resultId: "anvil", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_block","iron_block","iron_block", null,"iron_ingot",null, "iron_ingot","iron_ingot","iron_ingot"] },
  { id: "beacon", resultId: "beacon", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["glass","glass","glass", "glass","nether_star","glass", "obsidian","obsidian","obsidian"] },
  { id: "enchanting_table", resultId: "enchanting_table", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"book",null, "diamond","obsidian","diamond", "obsidian","obsidian","obsidian"] },
  { id: "brewing_stand", resultId: "brewing_stand", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, null,"blaze_rod",null, "cobblestone","cobblestone","cobblestone"] },
  { id: "cauldron", resultId: "cauldron", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["iron_ingot",null,"iron_ingot", "iron_ingot",null,"iron_ingot", "iron_ingot","iron_ingot","iron_ingot"] },
  { id: "bucket", resultId: "bucket", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "iron_ingot",null,"iron_ingot", null,"iron_ingot",null] },
  { id: "paper", resultId: "paper", resultCount: 3, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "sugar_cane","sugar_cane","sugar_cane", null,null,null] },
  { id: "book", resultId: "book", resultCount: 1, type: "shapeless", gridSize: "3x3", pattern: ["paper","paper","paper","leather",null,null,null,null,null], description: "3 paper and 1 leather (shapeless)" },
  { id: "lectern", resultId: "lectern", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["oak_slab","oak_slab","oak_slab", null,"bookshelf",null, null,"oak_planks",null] },
  { id: "clock", resultId: "clock", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"gold_ingot",null, "gold_ingot","redstone","gold_ingot", null,"gold_ingot",null] },
  { id: "compass", resultId: "compass", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"iron_ingot",null, "iron_ingot","redstone","iron_ingot", null,"iron_ingot",null] },
  { id: "map", resultId: "map", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["paper","paper","paper", "paper","compass","paper", "paper","paper","paper"] },
  // REDSTONE
  { id: "repeater", resultId: "repeater", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "redstone_torch","redstone","redstone_torch", "stone","stone","stone"] },
  { id: "comparator", resultId: "comparator", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"redstone_torch",null, "redstone_torch","quartz","redstone_torch", "stone","stone","stone"], description: "Uses nether quartz in the center" },
  { id: "piston", resultId: "piston", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","oak_planks","oak_planks", "cobblestone","iron_ingot","cobblestone", "cobblestone","redstone","cobblestone"] },
  { id: "sticky_piston", resultId: "sticky_piston", resultCount: 1, type: "shaped", gridSize: "2x2", pattern: ["slimeball","piston",null,null], description: "Place a slimeball on top of a piston" },
  { id: "lever", resultId: "lever", resultCount: 1, type: "shaped", gridSize: "2x2", pattern: ["stick","cobblestone",null,null] },
  { id: "tripwire_hook", resultId: "tripwire_hook", resultCount: 2, type: "shaped", gridSize: "3x3", pattern: [null,"iron_ingot",null, null,"stick",null, null,"oak_planks",null] },
  { id: "daylight_detector", resultId: "daylight_detector", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["glass","glass","glass", "quartz","quartz","quartz", "oak_slab","oak_slab","oak_slab"], description: "Glass on top, nether quartz in middle, oak slabs on bottom" },
  { id: "observer", resultId: "observer", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["cobblestone","cobblestone","cobblestone", "quartz","quartz","redstone", "cobblestone","cobblestone","cobblestone"] },
  { id: "target", resultId: "target", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"redstone",null, "redstone","hay_bale","redstone", null,"redstone",null], description: "Hay bale with redstone in cardinal positions" },
  { id: "redstone_torch", resultId: "redstone_torch", resultCount: 1, type: "shaped", gridSize: "2x2", pattern: ["redstone","stick",null,null] },
  { id: "redstone_lamp", resultId: "redstone_lamp", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"redstone",null, "redstone","glowstone","redstone", null,"redstone",null], description: "Glowstone surrounded by redstone" },
  // COMBAT
  { id: "bow", resultId: "bow", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,"stick","string", "stick",null,"string", null,"stick","string"] },
  { id: "crossbow", resultId: "crossbow", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["stick","iron_ingot","stick", null,"string",null, null,"tripwire_hook",null] },
  { id: "shield", resultId: "shield", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["oak_planks","iron_ingot","oak_planks", "oak_planks","oak_planks","oak_planks", null,"oak_planks",null] },
  { id: "arrow", resultId: "arrow", resultCount: 4, type: "shaped", gridSize: "3x3", pattern: [null,"flint",null, null,"stick",null, null,"feather",null] },
  { id: "tnt", resultId: "tnt", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["sand","gunpowder","sand", "gunpowder","sand","gunpowder", "sand","gunpowder","sand"], description: "Alternating sand and gunpowder" },
  // TRANSPORTATION
  { id: "minecart", resultId: "minecart", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "iron_ingot",null,"iron_ingot", "iron_ingot","iron_ingot","iron_ingot"] },
  { id: "chest_minecart", resultId: "chest_minecart", resultCount: 1, type: "shapeless", gridSize: "2x2", pattern: ["chest","minecart",null,null] },
  { id: "furnace_minecart", resultId: "furnace_minecart", resultCount: 1, type: "shapeless", gridSize: "2x2", pattern: ["furnace","minecart",null,null] },
  { id: "oak_boat", resultId: "oak_boat", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "oak_planks",null,"oak_planks", "oak_planks","oak_planks","oak_planks"] },
  // DECORATION
  { id: "painting", resultId: "painting", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["stick","stick","stick", "stick","white_wool","stick", "stick","stick","stick"] },
  { id: "item_frame", resultId: "item_frame", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["stick","stick","stick", "stick","leather","stick", "stick","stick","stick"] },
  { id: "flower_pot", resultId: "flower_pot", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "brick_item",null,"brick_item", null,"brick_item",null], description: "3 brick items in a V shape" },
  { id: "armor_stand", resultId: "armor_stand", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["stick","stick","stick", null,"stick",null, "stick","smooth_stone_slab","stick"] },
  { id: "white_carpet", resultId: "white_carpet", resultCount: 3, type: "shaped", gridSize: "3x3", pattern: [null,null,null, null,null,null, "white_wool","white_wool",null] },
  { id: "white_bed", resultId: "white_bed", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null, "white_wool","white_wool","white_wool", "oak_planks","oak_planks","oak_planks"] },
  { id: "white_banner", resultId: "white_banner", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["white_wool","white_wool","white_wool", "white_wool","white_wool","white_wool", null,"stick",null] },
  // MAGIC
  { id: "end_crystal", resultId: "end_crystal", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: ["glass","glass","glass", "glass","eye_of_ender","glass", "glass","ghast_tear","glass"] },
  { id: "eye_of_ender", resultId: "eye_of_ender", resultCount: 1, type: "shapeless", gridSize: "2x2", pattern: ["ender_pearl","blaze_powder",null,null] },
  { id: "fire_charge", resultId: "fire_charge", resultCount: 3, type: "shapeless", gridSize: "2x2", pattern: ["blaze_powder","coal","gunpowder",null], description: "Shapeless: blaze powder + coal + gunpowder yields 3" },
  // TOOLS
  { id: "fishing_rod", resultId: "fishing_rod", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,"stick", null,"stick","string", "stick",null,"string"] },
  { id: "flint_and_steel", resultId: "flint_and_steel", resultCount: 1, type: "shaped", gridSize: "2x2", pattern: ["iron_ingot",null,null,"flint"] },
  { id: "shears", resultId: "shears", resultCount: 1, type: "shaped", gridSize: "2x2", pattern: [null,"iron_ingot","iron_ingot",null] },
  { id: "lead", resultId: "lead", resultCount: 2, type: "shaped", gridSize: "3x3", pattern: ["string","string",null, "string","slimeball",null, null,null,"string"] },
  // NOT CRAFTABLE
  { id: "chainmail_helmet_nc", resultId: "chainmail_helmet", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null,null,null,null,null,null,null], description: "Not craftable. Obtained from mobs, trading, or chests." },
  { id: "chainmail_chestplate_nc", resultId: "chainmail_chestplate", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null,null,null,null,null,null,null], description: "Not craftable. Obtained from mobs, trading, or chests." },
  { id: "chainmail_leggings_nc", resultId: "chainmail_leggings", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null,null,null,null,null,null,null], description: "Not craftable. Obtained from mobs, trading, or chests." },
  { id: "chainmail_boots_nc", resultId: "chainmail_boots", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null,null,null,null,null,null,null], description: "Not craftable. Obtained from mobs, trading, or chests." },
  { id: "saddle_nc", resultId: "saddle", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null,null,null,null,null,null,null], description: "Not craftable. Found in chests in dungeons, temples, and villages." },
  { id: "name_tag_nc", resultId: "name_tag", resultCount: 1, type: "shaped", gridSize: "3x3", pattern: [null,null,null,null,null,null,null,null,null], description: "Not craftable. Found in chests or obtained by fishing." },
  { id: "netherite_pickaxe_nc", resultId: "netherite_pickaxe", resultCount: 1, type: "shaped", gridSize: "2x2", pattern: [null,null,null,null], description: "Not craftable in a standard table. Upgrade diamond pickaxe with a netherite ingot at a smithing table." },
  { id: "netherite_sword_nc", resultId: "netherite_sword", resultCount: 1, type: "shaped", gridSize: "2x2", pattern: [null,null,null,null], description: "Not craftable in a standard table. Upgrade diamond sword with a netherite ingot at a smithing table." },
];
